### ISSUE TITLE
Review `infra-backup-operator` for public listing on Charmhub

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/charmhub-listing-review#10]
### Charm name

infra-backup-operator

### Demo

https://charmhub.io/infra-backup-operator/docs/tutorial

### Project Repository

https://github.com/canonical/infra-backup-operator/

### CI Linting

https://github.com/canonical/infra-backup-operator/blob/main/.github/workflows/charm-analysis.yaml

### CI Release

https://github.com/canonical/infra-backup-operator/blob/main/.github/workflows/publish-charms.yaml

### CI Integration Tests

https://github.com/canonical/infra-backup-operator/blob/main/.github/workflows/charm-analysis.yaml

### Documentation Link

https://charmhub.io/infra-backup-operator/docs

**Comment by tonyandrewmeyer** [comment]
Hi @benhoyt! Please review this charm for listing, as we talked about the other day 😄. I'll try to keep an eye on the issue and automation, but if you find anything broken or have suggestions for the process, please open one/more regular issues for those and I'll get to them ASAP. I should be able to work around anything that breaks so that it doesn't block anything here. Thanks for being official guinea pig number one!

**Comment by benhoyt** [comment]
Copying to my own comment so I can edit and check things off:

## Listing requirements

* [ ] The charm does what it is meant to do, per the [demo or tutorial](https://charmhub.io/infra-backup-operator/docs/tutorial).
* [ ] The [charm's page on Charmhub](https://charmhub.io/infra-backup-operator) provides a quality impression. The overall appearance looks good and the [documentation](https://charmhub.io/infra-backup-operator/docs) looks reasonable.
* [ ] The charm has an icon.
* [ ] [Automated releasing](https://github.com/canonical/infra-backup-operator/blob/main/.github/workflows/publish-charms.yaml) to unstable channels exists
* [ ] [Integration tests](https://github.com/canonical/infra-backup-operator/blob/main/.github/workflows/charm-analysis.yaml) exist, are run on every change to the default branch, and are passing. At minimum, the tests verify that the charm can be deployed and ends up in a success state, and that the charm can be integrated with at least one example for each 'provides' and 'requires' specified (including optional, excluding tracing) ending up in a success state. The tests should be run with `charmcraft test`.

### Documentation

A charm's documentation should focus on the charm itself. For workload-specific or Juju-related content, link to the appropriate upstream documentation. A smaller charm can have single-page documentation for its description. A bigger charm should include a full Diátaxis navigation tree. Check that the charm has documentation that covers:
* [ ] How to use the charm, including configuration, limitations, and deviations in behaviour from the “non-charmed” version of the application.
* [ ] How to modify the charm
* [ ] A concise summary of the charm in the `charmcraft.yaml` 'summary' field, and a more detailed description in the `charmcraft.yaml` 'description' field.

### Best practices

The following best practices are recommended for all charms, and are also
required for listing.

* [ ] All charms should provide the commands configured by the Charmcraft profile, to allow easy testing across the charm ecosystem. It's fine to tweak the configuration of individual tools, or to add additional commands, but keep the command names and meanings that the profile provides.
* [x] Always include the ``optional`` key, rather than relying on the default value to indicate that the relation is required. Although this field is not enforced by Juju, including it makes it clear to users (and other tools) whether the relation is required.
* [ ] Bigger charm documentation examples:
* [ ] Capture output to `stdout` and `stderr` in your charm and use the logging and warning functionality to send messages to the charm user, rather than rely on Juju capturing output.  In particular, you should avoid `print()` calls, and ensure that any subprocess calls capture output.
* [ ] Documentation links should apply to the charm, and not to the application that is being charmed. Assume that the user already has basic competency in the use of the application.
* [ ] Don't duplicate model-level configuration options that are controlled by {external+juju:ref}`juju model-config <command-juju-model-config>`.
* [ ] Ensure that log messages are clear, meaningful, and provide enough information for the user to troubleshoot any issues. Avoid spurious logging. For instance, try not to log when event handlers are called, as the Juju controller does this automatically.
* [x] Ensure that the `pyproject.toml` *and* the lock file are committed to version control, so that exact versions of charms can be reproduced.
* [ ] Ensure that tooling is configured to automatically detect new versions, particularly security releases, for all your dependencies.
* [ ] For resources that are binary files, provide binaries for all the CPU architectures you intend to support.
* [ ] For very complex applications, consider providing configuration profiles, which can group values for large configs together. For example, a ``profile: large`` that tweaks multiple options under the hood to optimize for larger deployments, or a ``profile: ci`` for limited resource usage during testing.
* [ ] If you're setting up a ``git`` repository: name it using the pattern ``<charm name>-operator``. For the charm name, see :ref:`specify-a-name`.
* [ ] Just like Juju, a charm is an opinionated tool. Configure the application with the best defaults (ideally the application is deployable without providing any configuration at deploy time), and only expose application configuration options when necessary.
* [ ] Libraries should never mutate the status of a unit or application. Instead, use return values, or raise exceptions and let them bubble back up to the charm for the charm author to handle as they see fit.
* [ ] Name the repository using the pattern ``<charm name>-operator`` for a single charm, or ``<base charm name>-operators`` when the repository will hold multiple related charms. For the charm name, see {external+charmcraft:ref}`Charmcraft | Specify a name <specify-a-name>`.
* [ ] Never log credentials or other sensitive information.
* [ ] Prefer lowercase alphanumeric names, and use hyphens (-) to separate words. For charms that have already standardised on underscores, it is not necessary to change them, and it is better to be consistent within a charm then to have some action names be dashed and some be underscored.
* [x] Prefer lowercase alphanumeric names, separated with dashes if required. For charms that have already standardised on underscores, it is not necessary to change them, and it is better to be consistent within a charm then to have some config names be dashed and some be underscored.
* [x] Set the [`requires-python`](https://packaging.python.org/en/latest/specifications/pyproject-toml/#requires-python) version in your `pyproject.toml` so that tooling will detect any use of Python features not available in the versions you support.
* [ ] Smaller charm documentation examples:
* [x] The name should be slug-oriented (ASCII lowercase letters, numbers, and hyphens) and follow the pattern ``<workload name in full>[<function>][-k8s]``. For example, ``argo-server-k8s``.
* [ ] The quality assurance pipeline of a charm should be automated using a continuous integration (CI) system.
* [ ] The quality assurance pipeline of a charm should be automated using a continuous integration (CI) system.
* [ ] When using the `charm` plugin with charmcraft, ensure that you set strict dependencies to true. For example:

**Comment by benhoyt** [comment]
Hi @gabrielcocenza, this charm looks good, and very close to ready for public listing. I've also run through the tutorial, and it worked nicely (though see minor notes below). Per the checklist above, a couple of things that will be required first:

- It's missing an `icon.svg` for the Charmhub icon. See https://documentation.ubuntu.com/charmcraft/stable/reference/files/icon-svg-file/
- Is dependabot set up for the repo? I wasn't able to see. That's for the item "Ensure that tooling is configured to automatically detect new versions, particularly security releases, for all your dependencies."

A few other things that would be good to fix but won't block listing:

- When doing the tutorial, I needed to add `--channel edge` to the "juju deploy velero-operator" and "juju deploy infra-backup-operator" commands.
- The tutorial wasn't clear what `<YOUR_IP>` was. Would be good to change to `<MICROCEPH_IP>` with a comment like "<MICROCEPH_IP> from sudo microceph status" or similar.
- The `CONTRIBUTING.md` doc mentions pytest-operator, but the integration tests actually use Jubilant and pytest-jubilant, so this should be updated.

**Comment by gabrielcocenza** [comment]
Hi @benhoyt

Thanks for your review

- https://github.com/canonical/infra-backup-operator/pull/12/files -> Fixed missing icon.svg and jubilant
- Dependabot is set like this:

<img width="900" height="599" alt="Image" src="https://github.com/user-attachments/assets/ab52e138-2ed2-4697-b8c8-ec77e443e69e" />

I guess it's right

- [Fixed edge channel](https://charmhub.io/infra-backup-operator/docs/tutorial?channel=latest/edge#p-38581-deploy)
- Fixed the [MICROCEPH_IP](https://charmhub.io/infra-backup-operator/docs/tutorial?channel=latest/edge#p-38581-integrate)

**Comment by benhoyt** [comment]
Great, thanks for that updates. Couple more questions:

- Icon: have you published to Charmhub yet? It looks like the icon is still not showing up there (still has the placeholder) -- any idea why?
- Dependabot settings look fine.

**Comment by benhoyt** [comment]
@gabrielcocenza See above. (Not sure if you'll be subscribed to this issue or not, so mentioning you explicitly.)

**Comment by gabrielcocenza** [comment]
I have no idea why the icon is not showing up. The webpage says that the icon is valid

<img width="883" height="527" alt="Image" src="https://github.com/user-attachments/assets/13e4f864-fce0-43dd-a4c5-36526eb5fe3f" />


I've created a new PR to fix the remaining references about pytest-operator at: https://github.com/canonical/infra-backup-operator/pull/13

**Comment by benhoyt** [comment]
Thanks. Not sure about the icon! Given all the other items are done, we'll consider this approved, and I'll ask the store team to list it, as well as ask them why the icon isn't showing up.

**Comment by benhoyt** [comment]
@gabrielcocenza Per the store team, regarding the listing and the icon:

> I have listed the charm, but charms will not show up unless they are defaulted to a channel that has a stable release. Also I think the icon not updating is also related to this. After the first release, metadata updates only happen on releases to stable risk.
